### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by cjnucette** [adrian5/oceanic-next-vim#1]
Hi, great theme. I would be nice if there were an option to make `EndOfBuffer` the same as the background, so the squiggly lines at the end of the file don't show.

**Comment by adrian5** [comment]
Hi, I can definitely see why one may wish to do that, but it's very specific and I'm not sure I want to add another global option just for that detail. Is this a common option in other colorschemes?

As workaround, you could do:

```viml
colorscheme oceanicnext
hi EndOfBuffer ctermfg=235 guifg=#1b2b34

" If you only use truecolor terminals
hi EndOfBuffer guifg=bg

" If you only use 256-color terminals
hi EndOfBuffer ctermfg=bg

" Use same background as gutter:
hi EndOfBuffer ctermfg=234 ctermbg=234 guifg=#192932 guibg=#192932
```

**Comment by cjnucette** [comment]
Ok, thanks.
