### ISSUE TITLE
barbar inactive modified color

### ISSUE THREAD

**Issue by ranebrown** [adrian5/oceanic-next-vim#5]
I find the yellow used for a modified inactive tab in barbar too distracting. Any chance you would consider changing it to something similar to a comment color? I'm using #7f7b66 right now which seems pretty good. Thanks!

**Comment by adrian5** [comment]
I'll look into it later, it's currently not my daily driver. I recall the defaults were very strong, and I didn't want to alienate barbar users by making it look too subtle in my theme. I'll be sure to try your color.

**Comment by adrian5** [comment]
Yeah, agreed. The current yellow is too prominent.

What do you think about making inactive-mod a faded green?

![barbar-example-1](https://user-images.githubusercontent.com/5426924/100516745-3afd7580-3186-11eb-9f9c-81e7981e0af3.png)
NOTE: I recommend viewing this image against a dark background (open image in new tab may suffice); the contrast always looks too soft against the white GitHub page.

I think this makes semantic sense:

| | active | inactive |
| --- | --- | --- |
| norm | fg | fg-faded |
| mod | green | green-faded |

The only concern is that this is too hard to distinguish under bad lighting conditions. A different hue like your faded yellow would be better then.

**Comment by ranebrown** [comment]
I agree it makes sense to have them the same color. I'll leave it up to you whether that should be green like you have here or switch them both to yellow. I think either would work.

**Comment by adrian5** [comment]
I definitely want to keep green for active-modified. Green feels like an affirmative _"this file can be saved now"_. Yellow is more of a warning color, but if I need it for contrast then so be it. For mod-inactive that could mean _"don't forget this file"_. 

If you want, you can try the dev branch and see how it looks:

```viml
Plug 'adrian5/oceanic-next-vim', { 'branch': 'dev' }
```

If that works for you, I'll publish it like that. As mentioned, the contrast of mod-inactive against normal-inactive is kind of weak, but I can't make the faded green any stronger or it will shift too close to mod-active.

Btw, I appear to have missed a few other visual details the first time around, so it payed off to revisit barbar.

**Comment by ranebrown** [comment]
Looks good to me 👍

**Comment by adrian5** [comment]
Ok, great. I'll publish it as such then. If it turns out to be subpar in the long run, it can be tweaked again.

Thanks for the report!
