### ISSUE TITLE
Kitty Terminal Port?

### ISSUE THREAD

**Issue by bakageddy** [adrian5/oceanic-next-vim#8]
Hey, I recently discovered this colourscheme and it's very awesome, I was hoping to find a kitty theme to match; but unfortunately, I can't find a single one. Thanks for reading.

**Comment by adrian5** [comment]
Hey there, glad you like the theme! I'm currently writing a successor in Lua (targeting the modern neovim plugin ecosystem), which I can hopefully release soon, probably under a slightly different name to avoid the current name clash.

While I have no plans to supply styling for other applications, I happen to have used Kitty in the past, so you can try these values from my old `kitty.conf`:

```shell
# Colorscheme (Oceanic Next)
background #1b2b34
foreground #d8dee9
cursor #c4c8c5
selection_background #2f4c5c
selection_foreground #d8dee9
color0 #29414f
color8 #405860
color1 #ec5f67
color9 #ec5f67
color2 #99c794
color10 #99c794
color3 #fac863
color11 #fac863
color4 #6699cc
color12 #6699cc
color5 #c594c5
color13 #c594c5
color6 #5fb3b3
color14 #5fb3b3
color7 #65737e
color15 #adb5c0

```

**Comment by bakageddy** [comment]
Thanks, this is good enough for me! I will close this issue.
